repos:
  # for Python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: ["--select=F401", "--fix"]
      - id: ruff-format
  
  # for C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
        args: [--style=file]

  - repo: https://github.com/danmar/cppcheck
    rev: v2.6
    hooks:
      - id: cppcheck
        args: [--enable=all]

  - repo: https://github.com/llvm/llvm-project
    rev: llvmorg-13.0.0
    hooks:
      - id: clang-tidy
        args: [--checks=-*,modernize-*]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
        args: [--style=file]

  - repo: https://github.com/danmar/cppcheck
    rev: v2.6
    hooks:
      - id: cppcheck
        args: [--enable=all]